# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dd597957789ec97321b8b11d012f5d58623c7c029fb9fc99428868f64c2d1a0a7814b84eed36da75f32fbd35beedb0202de743ef4b3eb1769f749114b239137

test:
  secret_key_base: 7fcc017331ad2f44366022658fb22790ff8f7fca577a8216585f258f024d9967ffd94b97c553f3fb14992ebd85d5d6d4331b97d7d7be888c7dedae6050f26fa6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
